import Head from 'next/head'
import { NextPage } from 'next'
import { Home } from '../components/organisms/Home'
import React, { createContext, useContext } from 'react'
import { Material } from '../types'
import useSWR from 'swr'
import axios from 'axios'
import { AuthContext, AuthStatus } from '../lib/auth'

export const MaterialContext: React.Context<Material[]> = createContext<Material[]>([])

const fetcher = (authState: 'guest' | 'authed' | 'none') => {
  if (authState === 'guest') {
    return axios.get('/api/materials').then((res) => res.data)
  } else if (authState === 'authed') {
    // TODO: Firebaseを叩く
    return axios.get('/api/materials').then((res) => res.data)
  } else {
    return {
      data: [],
      error: undefined,
    }
  }
}

export const Index: NextPage = () => {
  const currentUser = useContext(AuthContext)

  let materials: Material[] = []
  const key = currentUser ? 'authed' : currentUser === AuthStatus.NOT_LOGIN ? 'guest' : 'none'
  const { data, error } = useSWR(key, fetcher)
  if (!error) {
    // @ts-ignore
    materials = data?.materials
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <MaterialContext.Provider value={materials || []}>
        <Home />
      </MaterialContext.Provider>
    </>
  )
}

export default Index
