import Head from 'next/head'
import { NextPage } from 'next'
import React from 'react'
import { Editor } from '../components/organisms/Editor'
import { getAuth, GoogleAuthProvider, onAuthStateChanged, signInWithRedirect } from 'firebase/auth'
import { initializeApp } from 'firebase/app'

interface Props {}

export const Login: NextPage<Props> = (props) => {
  return (
    <>
      <Head>
        <title>ログイン</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
    </>
  )
}

export default Login
