import Head from 'next/head'
import { NextPage } from 'next'
import React from 'react'
import { Editor } from '../components/organisms/Editor'

interface Props {}

export const Register: NextPage<Props> = (props) => {
  return (
    <>
      <Head>
        <title>素材を登録</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <Editor />
    </>
  )
}

export default Register
