import Head from 'next/head'
import { NextPage } from 'next'
import React from 'react'
import { Editor } from '../components/organisms/Editor'
import { SubmitHandler, useForm } from 'react-hook-form'
import { RegisterForm } from '../types'
import { yupResolver } from '@hookform/resolvers/yup'
import { schema } from '../lib/validation'
import Axios from 'axios'
import { useRouter } from 'next/router'

interface Props {}

export const Register: NextPage<Props> = (props) => {
  const router = useRouter()

  const {
    register,
    handleSubmit,
    formState: { errors, dirtyFields },
  } = useForm<RegisterForm>({
    mode: 'all',
    resolver: yupResolver(schema, {
      abortEarly: false,
    }),
    criteriaMode: 'all',
  })

  const filterCelsiusInput = (
    event: React.KeyboardEvent<HTMLInputElement> | React.CompositionEvent<HTMLInputElement>
  ) => {
    if ('key' in event && !['1', '2', '3', '4', '5', '6', '7', '8', '9', '0'].includes(event.key)) {
      event.preventDefault()
      return false
    }

    if ('data' in event && !/^\d+$/.test(event.data)) {
      event.preventDefault()
      return false
    }
    return true
  }

  const inputTagAttributes = {
    plasticImage: register('plasticImage', { required: true }),
    keycapImage: register('keycapImage', { required: true }),
    materialName: register('materialName', { required: true }),
    colorType: register('colorType', { required: true }),
    plasticType: register('plasticType', { required: true }),
    celsius: {
      onKeyPress: filterCelsiusInput,
      ...register('celsius', { required: true, setValueAs: (v) => v.replace(/\D/g, '') }),
    },
    note: register('note'),
  }

  const executeSubmit: SubmitHandler<RegisterForm> = async (rawData) => {
    const data = new FormData()
    data.append('plasticImage', rawData.plasticImage[0])
    data.append('keycapImage', rawData.keycapImage[0])
    data.append('materialName', rawData.materialName)
    data.append('colorType', rawData.colorType)
    data.append('plasticType', rawData.plasticType)
    data.append('celsius', rawData.celsius.toString())
    data.append('note', rawData.note)

    const response = await Axios.post('/api/register', data, {
      headers: {
        'content-type': 'multipart/form-data',
      },
    })

    if (response.status === 200) {
      await router.push({
        // @ts-ignore TODO: 型を書く
        pathname: `/material/${response.data.materialId}`,
        query: { action: 'register' },
      })
    }
  }

  const errorsPresented = {
    plasticImage: dirtyFields.plasticImage === true ? errors.plasticImage?.message || null : null,
    keycapImage: dirtyFields.keycapImage === true ? errors.keycapImage?.message || null : null,
    materialName: dirtyFields.materialName === true ? errors.materialName?.message || null : null,
    colorType: dirtyFields.colorType === true ? errors.colorType?.message || null : null,
    plasticType: dirtyFields.plasticType === true ? errors.plasticType?.message || null : null,
    celsius: dirtyFields.celsius === true ? errors.celsius?.message || null : null,
    note: dirtyFields.note === true ? errors.note?.message || null : null,
  }

  const canSubmit = Object.keys(errors).length === 0

  return (
    <>
      <Head>
        <title>素材を登録</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <Editor
        inputTagAttributes={inputTagAttributes}
        errorMessage={errorsPresented}
        onClickSubmit={handleSubmit(executeSubmit)}
        canSubmit={canSubmit}
      />
    </>
  )
}

export default Register
